const ROLES = {
  USER: 'USER',
  SUBJECT_ADMIN: 'SUBJECT_ADMIN',
  ADMIN: 'ADMIN',
  OWNER: 'OWNER'
}

const RESOURCE_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  FLAGGED: 'FLAGGED',
  DELETED: 'DELETED'
}

const RESOURCE_TYPES = {
  NOTES: 'NOTES',
  QUESTION_BANK: 'QUESTION_BANK',
  PROJECT_ARCHIVE: 'PROJECT_ARCHIVE'
}

module.exports = {
  ROLES,
  RESOURCE_STATUS,
  RESOURCE_TYPES
}
